services:
  backend:
    platform: linux/arm64
    build:
      context: ../..
      dockerfile: ./docker/Dockerfile.prod
      args:
        - AWS_IAM_ACCESS_KEY=${AWS_IAM_ACCESS_KEY}
        - AWS_IAM_SECRET_KEY=${AWS_IAM_SECRET_KEY}
    image: sjhn/momori-backend:prod-latest
    restart: always
    ports:
      - 8080:8080
