FROM openjdk:21-jdk as builder
WORKDIR /backend

ARG JAR_PATH=momori-0.1-SNAPSHOT.jar
COPY ${JAR_PATH} app.jar

ARG AWS_IAM_ACCESS_KEY
ARG AWS_IAM_SECRET_KEY
ENV AWS_IAM_ACCESS_KEY=${AWS_IAM_ACCESS_KEY}
ENV AWS_IAM_SECRET_KEY=${AWS_IAM_SECRET_KEY}

ENTRYPOINT [ "java", "-jar", "-Dspring.profiles.active=prod", "app.jar" ]