services:
  backend:
    platform: linux/arm64
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.prod
      args:
        - OAUTH2_GITHUB_CLIENT_ID=${OAUTH2_GITHUB_CLIENT_ID}
        - OAUTH2_GITHUB_CLIENT_SECRET_ID=${OAUTH2_GITHUB_CLIENT_SECRET_ID}
        - OAUTH2_NAVER_CLIENT_ID=${OAUTH2_NAVER_CLIENT_ID}
        - OAUTH2_NAVER_CLIENT_SECRET_ID=${OAUTH2_NAVER_CLIENT_SECRET_ID}
        - OAUTH2_KAKAO_CLIENT_ID=${OAUTH2_KAKAO_CLIENT_ID}
        - OAUTH2_KAKAO_CLIENT_SECRET_ID=${OAUTH2_KAKAO_CLIENT_SECRET_ID}
        - OAUTH2_DISCORD_CLIENT_ID=${OAUTH2_DISCORD_CLIENT_ID}
        - OAUTH2_DISCORD_CLIENT_SECRET_ID=${OAUTH2_DISCORD_CLIENT_SECRET_ID}
        - MYSQL_MASTER_DB_HOST=${MYSQL_MASTER_DB_HOST}
        - MYSQL_USERNAME=${MYSQL_USERNAME}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MONGODB_HOST=${MONGODB_HOST}
        - MONGODB_DATABASE=${MONGODB_DATABASE}
        - OAUTH2_JWT_SECRET_KEY=${OAUTH2_JWT_SECRET_KEY}
        - S3_REGION=${S3_REGION}
        - S3_BUCKET_NAME=${S3_BUCKET_NAME}
        - AWS_IAM_ACCESS_KEY=${AWS_IAM_ACCESS_KEY}
        - AWS_IAM_SECRET_KEY=${AWS_IAM_SECRET_KEY}
        - REDIS_HOST=${REDIS_HOST}
        - REDIS_PORT=${REDIS_PORT}
        - REDIS_USERNAME=${REDIS_USERNAME}
        - REDIS_PASSWORD=${REDIS_PASSWORD}
    image: sjhn/momori-backend:prod-lastest
    restart: always
    ports:
      - 8080:8080
