spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: poolygo
  profiles:
    include:
      - oauth
      - data
      - aws

url:
  base:
    prod: https://poolygo.com
    dev: http://localhost:5173
  path:
    signup: /register
    auth: /auth

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
#    org.mongodb.driver: DEBUG
#    org.mongodb.driver.protocol.command: DEBUG