spring:
  config:
    import:
      - optional:file:.env[.properties]
#      - aws-parameterstore:/config/
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: ${momori.mysql.master-db-host}
    username: ${momori.mysql.username}
    password: ${momori.mysql.password}

  data:
    mongodb:
      uri: ${momori.mongodb.host}
      database: ${momori.mongodb.database}
    redis:
      host: ${momori.redis.host}
      port: ${momori.redis.port}
      username: ${momori.redis.username}
      password: ${momori.redis.password}


#logging:
#  level:
#    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
#    org.mongodb.driver: DEBUG