spring:
  config:
    import:
      - optional:file:.env[.properties]
      - aws-parameterstore:/config/
  application:
    name: poolygo
  profiles:
    include:
      - oauth
      - data
      - aws
  cloud:
    aws:
      region:
        static: ap-northeast-2
      credentials:
        access-key: ${AWS_IAM_ACCESS_KEY}
        secret-key: ${AWS_IAM_SECRET_KEY}

url:
  base:
    prod: https://poolygo.com
    dev: http://localhost:5173
  path:
    signup: /register
    auth: /auth

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
#    org.springframework.security: DEBUG
#    com.poolygo.auth: DEBUG
#    org.mongodb.driver: DEBUG
#    org.mongodb.driver.protocol.command: DEBUG