spring:
  application:
    name: poolygo
  profiles:
    include:
      - oauth
      - data

url:
  base:
    prod: https://poolygo.com
    dev: http://localhost:5173
  path:
    signup: /register
    auth: /auth