spring:
  config:
    import: optional:file:.env[.properties]

cloud:
  aws:
    s3:
      bucket: ${momori.s3.bucket-name}
    credentials:
      access-key: ${AWS_IAM_ACCESS_KEY}
      secret-key: ${AWS_IAM_SECRET_KEY}
    region:
      static: ${momori.s3.region}

