spring:
  config:
    import: optional:file:.env[.properties]
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: ${MYSQL_MASTER_DB_HOST}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  data:
    mongodb:
      uri: ${MONGODB_HOST}
      database: ${MONGODB_DATABASE}
#      uri: mongodb+srv://jh:jh980101^^@poolygo-cluster.g7kmw.mongodb.net/?retryWrites=true&w=majority&appName=poolygo-cluster
#      database: poolygo


#logging:
#  level:
#    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
#    org.mongodb.driver: DEBUG