spring:
  config:
    import: optional:file:.env[.properties]
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: ${MASTER_DATASOURCE}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

#  data:
#    mongodb:
#      uri:
#      password:
