spring:
  config:
    import: optional:file:.env[.properties]
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: ${datasource.address.master}
    username: ${datasource.username}
    password: ${datasource.password}

  data:
    mongodb:
      uri: ${datasource.mongodb.url}
      database: ${datasource.mongodb.database}