spring:
  config:
    import: optional:file:.env[.properties]
  security:
    oauth2:
      client:
        registration:
#          google:
#            client-id: 197161588086-3bngrg3te711c8hqp7e4m8ltmlibvn2j.apps.googleusercontent.com
#            client-secret: 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
#            scope: profile,email
          github:
            client-name: Github
            client-id: ${GITHUB_OAUTH2_CLIENT_ID}
            client-secret: ${GITHUB_OAUTH2_CLIENT_SECRET}
          naver:
            client-name: Naver
            client-id: ${NAVER_OAUTH2_CLIENT_ID}
            client-secret: ${NAVER_OAUTH2_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
jwt:
  secret-key: ${JWT_SECRET_KEY}