spring:
  config:
    import: optional:file:.env[.properties]
  security:
    oauth2:
      client:
        registration:
          github:
            client-name: Github
            client-id: ${oauth2.github.client-id}
            client-secret: ${oauth2.github.client-secret}
          naver:
            client-name: Naver
            client-id: ${oauth2.naver.client-id}
            client-secret: ${oauth2.naver.client-secret}
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
          kakao:
            client-name: Kakao
            client-id: ${oauth2.kakao.client-id}
            client-secret: ${oauth2.kakao.client-secret}
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: client_secret_post
          discord:
            client-name: Discord
            client-id: ${oauth2.discord.client-id}
            client-secret: ${oauth2.discord.client-secret}
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/discord
            scope: identify,email
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize # "인가 코드 받기" 항목
            token-uri: https://kauth.kakao.com/oauth/token # "토큰 받기" 항목
            user-info-uri: https://kapi.kakao.com/v2/user/me # "사용자 정보 가져오기" 항목
            user-name-attribute: id # 식별자 . 카카오의 경우 "id" 사용
          discord:
            authorization-uri: https://discord.com/oauth2/authorize
            token-uri: https://discord.com/api/oauth2/token
            user-info-uri: https://discord.com/api/v10/users/@me
            user-name-attribute: id

jwt:
  secret-key: ${oauth2.jwt.secret-key}